name: download-videos

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARGS: ${{ inputs.args }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build JS Files
        run: |
          npm install
          npm run build-download-videos

      - name: Prepare workspace
        run: |
          mv download-videos/* ./

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: Install yt-dlp
        run: python -m pip install -U yt-dlp

      - name: Prepare yt-dlp commands
        run: |
          node dist/index.js prepare-env ytDlp

      - name: Download video
        run: |
          ${{ env.COMMANDS }}

      - name: Prepare random name
        run: |
          node dist/index.js prepare-env RANDOM_NAME

      - name: Compress file
        run: |
          zip -9 -r artifact_${{ env.RANDOM_NAME }}.zip downloads

      - name: Upload artifact
        run: |
          curl -sL https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh | sh
          ./transfer gg ./artifact_${{ env.RANDOM_NAME }}.zip
