name: download-videos-lux

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARGS: ${{ inputs.args }}
    steps:
      - name: 检出仓库 / Clone repository
        uses: actions/checkout@v2

      - name: 构建 JS 文件 / Build JS Files
        run: |
          npm install
          npm run build-download-videos-lux

      - name: 准备工作空间 / Prepare workspace
        run: |
          mv download-videos-lux/* ./
          mkdir temp
          mkdir downloads

      - name: 安装 ffmpeg / Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: 准备下载 lux / Prepare download lux commands
        run: node dist/index.js prepare-env downloadLux

      - name: 下载 lux / Download lux
        run: |
          ${{ env.COMMANDS }}
          tar -zxvf downloads/lux.tar.gz

      - name: 准备下载 / Prepare lux commands
        run: node dist/index.js prepare-env lux

      - name: 下载视频 / Download video
        run: ${{ env.COMMANDS }}

      - name: 压缩文件 / Compress file
        run: zip -9 -r artifact_${{ github.run_id }}.zip downloads

      - name: 准备上传 / Prepare transfer commands
        run: node dist/index.js prepare-env transfer

      - name: 上传成品 / Upload artifact
        run: ${{ env.COMMANDS }}
