name: download-videos

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARGS: ${{ inputs.args }}
    steps:
      - name: 检出仓库 / Clone repository
        uses: actions/checkout@v2

      - name: 构建 JS 文件 / Build JS Files
        run: |
          npm install
          npm run build-download-videos

      - name: 准备工作空间 / Prepare workspace
        run: |
          mv download-videos/* ./

      - name: 安装 Python / Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 安装 ffmpeg / Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: 安装 yt-dlp / Install yt-dlp
        run: python -m pip install -U yt-dlp

      - name: 准备下载 / Prepare yt-dlp commands
        run: |
          node dist/index.js prepare-env ytDlp

      - name: 下载视频 / Download video
        run: |
          ${{ env.COMMANDS }}

      - name: 压缩文件 / Compress file
        run: |
          zip -9 -r artifact_${{ github.run_id }}.zip downloads

      - name: 准备上传 / Prepare transfer commands
        run: |
          node dist/index.js prepare-env transfer

      - name: 上传成品 / Upload artifact
        run: |
          ${{ env.COMMANDS }}
