name: download-videos

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARGS: ${{ inputs.args }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Create Env State
        run: |
          npm install
          npm run build-create-env-state
          node workflow-distributor/dist/index.js
      - name: Prepare workspace
        run: mv download-videos/* ./
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg
      - name: Install yt-dlp
        run: python -m pip install -U yt-dlp
      - name: Download video
        run: yt-dlp --config-location config.txt
      - name: Compress file
        run: zip -9 -r artifact.zip downloads
      - name: Upload artifact
        run: |
          curl -sL https://git.io/file-transfer | sh
          ./transfer trs ./artifact.zip
