name: separate-audios

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
#      - name: Set up ffmpeg
#        uses: FedericoCarboni/setup-ffmpeg@v1
#        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
#          token: ${{ secrets.GITHUB_TOKEN }}
#        id: setup-ffmpeg
      # - name: Install libsndfile
      #   run: sudo apt install libsndfile
#      - name: Install spleeter
#        run: |
#          python -m pip install -U spleeter
      - name: Separate audio
        run: |
          cd separate-audios
          python separate-audio.py
      - name: Compress file
        run: |
          cd separate-audios
          zip -9 -r artifact.zip audio_output
      - name: Upload artifact
        run: |
          cd separate-audios
          curl -sL https://git.io/file-transfer | sh
          ./transfer trs ./artifact.zip