name: separate-audios

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARGS: ${{ inputs.args }}
    steps:
      - name: 检出仓库 / Clone repository
        uses: actions/checkout@v2

      - name: 构建 JS 文件 / Build JS Files
        run: |
          npm install
          npm run build-separate-audios

      - name: 准备工作空间 / Prepare workspace
        run: |
          mv separate-audios/* ./
          mkdir downloads
          mkdir segments
          mkdir separates
          mkdir outputs

      - name: 安装 Python / Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 安装 ffmpeg / Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1

      # - name: Install libsndfile
      #   run: sudo apt install libsndfile

      - name: 安装 Spleeter / Install spleeter
        run: |
          python -m pip install -U spleeter

      - name: 准备下载 / Prepare download commands
        run: |
          node dist/index.js prepare-env downloadFiles

      - name: 下载文件 / Download files
        run: |
          ${{ env.COMMANDS }}

      - name: 准备分割音频 / Prepare split audios commands
        run: |
          node dist/index.js prepare-env ffmpegSplit

      - name: 分割音频 / Split audios
        run: |
          ${{ env.COMMANDS }}

      - name: 准备分离人声 / Prepare spleeter commands
        run: |
          node dist/index.js prepare-env spleeter

      - name: 分离人声 /Separate audio
        run: |
          ${{ env.COMMANDS }}

      - name: 准备拼接音频 / Prepare concat audios commands
        run: |
          node dist/index.js prepare-env ffmpegConcat

      - name: 拼接音频 / Concat audios
        run: |
          ${{ env.COMMANDS }}

      - name: 压缩文件 / Compress file
        run: |
          zip -9 -r artifact_${{ github.run_id }}.zip outputs

      - name: 准备上传 / Prepare transfer commands
        run: |
          node dist/index.js prepare-env transfer

      - name: 上传成品 / Upload artifact
        run: |
          ${{ env.COMMANDS }}
