name: separate-audios

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARGS: ${{ inputs.args }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build JS Files
        run: |
          npm install
          npm run build-separate-audios

      - name: Prepare workspace
        run: |
          mv separate-audios/* ./

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      # - name: Install libsndfile
      #   run: sudo apt install libsndfile

      - name: Install spleeter
        run: |
          python -m pip install -U spleeter

      - name: Prepare download options
        run: |
          node dist/index.js prepare-env DOWNLOAD_OPTIONS

      - name: Download files
        run: |
          mkdir audios
          mkdir downloads
          curl -kL ${{ env.DOWNLOAD_OPTIONS }}

      - name: Extract files
        if: ${{ env.FILE_ARCHIVE == 'zip' }}
        run: |
          unzip -co -d audios/ downloads/archive.zip

      - name: Prepare spleeter options
        run: |
          node dist/index.js prepare-env SPLEETER_OPTIONS

      - name: Separate audio
        run: |
          node dist/index.js exec-spleeter

      - name: Compress file
        run: |
          zip -9 -r artifact.zip audio_output

      - name: Upload artifact
        run: |
          curl -sL https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh | sh
          ./transfer trs ./artifact.zip
