name: test

on:
  workflow_call:
    inputs:
      args:
        type: string

jobs:
  build:
    env:
      ARGS: ${{ inputs.args }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库 / Checkout Repository
        uses: actions/checkout@v2

      - id: step1
        run: |
          echo '${{ env.ARGS }}'

      - id: step2
        run: pwd

      - id: step3
        run: ls -l
