name: workflow-distributor

on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]

jobs:
  distributor:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.distribute.outputs.run }}
      args: ${{ steps.distribute.outputs.args }}
    steps:
      - name: 检出仓库 / Checkout Repository
        uses: actions/checkout@v2
      - id: distribute
        name: 分配任务 / Distribute Tasks
        run: |
          npm install
          npm run build-distribute
          node workflow-distributor/dist/index.js

  test:
    needs: distributor
    with:
      args: ${{ needs.distributor.outputs.args }}
    if: ${{ needs.distributor.outputs.run == 'test' }}
    uses: ./.github/workflows/test.yaml

  separate-audios:
    needs: distributor
    with:
      args: ${{ needs.distributor.outputs.args }}
    if: ${{ needs.distributor.outputs.run == 'separate-audios' }}
    uses: ./.github/workflows/separate-audios.yaml

  download-videos-dlp:
    needs: distributor
    with:
      args: ${{ needs.distributor.outputs.args }}
    if: ${{ needs.distributor.outputs.run == 'download-videos-dlp' }}
    uses: ./.github/workflows/download-videos-dlp.yaml

  download-videos-lux:
    needs: distributor
    with:
      args: ${{ needs.distributor.outputs.args }}
    if: ${{ needs.distributor.outputs.run == 'download-videos-lux' }}
    uses: ./.github/workflows/download-videos-lux.yaml
